### ISSUE TITLE
Incorrect number / timeout

### ISSUE THREAD

**Issue by dotgodly** [phiphou/vine-backup#5] opened 2017-01-13 04:28 UTC
With just email and password set, the app only retrieves 181 vines. With --likes set, it times out. I have 995 posts and 11,940 likes.

**Comment by phiphou** [comment] 2017-01-13 12:41
Unable to reproduce without your Vine user name. Maybe you should try the --list option.

**Comment by dotgodly** [comment] 2017-01-13 17:33
--list still gives me 181 vines. My user ID is 996123084295905280.

**Comment by phiphou** [comment] 2017-05-07 19:59
Vine api is not responding anymore, so I"m closing this.

**Closed as completed by phiphou** 2017-05-07 19:59 UTC
